'use strict';
// Texts of the inspection report (lib/report.js), Slovak and English.

const SK = {
  lang: 'sk',
  fileName: 'Sprava-o-dokumentacii',
  'sheet.summary': 'Súhrn',
  'sheet.register': 'Dokumenty',
  'sheet.reviewsDue': 'Revízie – termíny',
  'sheet.reviewsDone': 'Vykonané revízie',
  'sheet.laws': 'Predpisy',
  'sheet.changes': 'Zmeny legislatívy',
  'sheet.decisions': 'Rozhodnutia',
  'sheet.trainingMissing': 'Chýbajúce školenia',
  'sheet.trainingRecords': 'Školenia',
  'sheet.approvals': 'Schvaľovanie',
  'sheet.copies': 'Riadené kópie',
  'sheet.notices': 'Oznamy úradov',
  title: 'Správa o riadenej dokumentácii',
  period: 'Obdobie',
  periodAll: 'Celé obdobie',
  generated: 'vytvorené {date} v aplikácii SOP Archív',
  footer: 'Správa je výpis z aplikácie SOP Archív. Úplná história (kto, kedy, čo) je v auditnom zázname aplikácie. Podpisy v aplikácii sú potvrdené heslom používateľa.',
  none: 'Žiadne záznamy.',
  sumDocs: 'riadených dokumentov',
  sumEffective: '{n} platných',
  sumOverdue: 'revízií po termíne',
  sumDue: 'revízií v najbližších 60 dňoch',
  sumChanges: 'otvorených zmien legislatívy',
  sumDecisions: 'rozhodnutí „neplatí pre nás / platí naša SOP“',
  sumTraining: 'chýbajúcich zaškolení',
  sumCopies: 'kópií na stiahnutie',
  register: 'Zoznam riadených dokumentov',
  reviewsDue: 'Revízie po termíne a blížiace sa',
  reviewsDone: 'Vykonané revízie',
  laws: 'Sledované právne predpisy',
  changes: 'Zmeny legislatívy a ich posúdenie',
  decisions: 'Rozhodnutia spoločnosti k ustanoveniam predpisov',
  trainingMissing: 'Chýbajúce zaškolenie na aktuálnu verziu',
  trainingRecords: 'Záznamy o školení',
  approvals: 'Schvaľovanie verzií',
  copies: 'Riadené kópie',
  code: 'Kód',
  title_: 'Názov',
  version: 'Verzia',
  status: 'Stav',
  department: 'Útvar',
  effective: 'Účinnosť od',
  review: 'Revízia do',
  approver: 'Schválil',
  approvedInApp: 'Schválené v aplikácii',
  trainingCol: 'Zaškolení',
  lawsCol: 'Cituje predpisy',
  days: 'Termín',
  overdueBy: 'po termíne {n} dní',
  inDays: 'o {n} dní',
  date: 'Dátum',
  by: 'Kto',
  outcome: 'Výsledok',
  next: 'Ďalšia revízia',
  notes: 'Poznámka',
  law: 'Predpis',
  lawVersion: 'Známe znenie',
  checked: 'Skontrolované',
  checkStatus: 'Stav kontroly',
  citingDocs: 'Dokumentov',
  kind: 'Druh',
  effectiveFrom: 'Platí od',
  detected: 'Zistené',
  affected: 'Dotknuté dok.',
  resolution: 'Uzavretie',
  section: 'Ustanovenie',
  wholeAct: 'celý predpis',
  art: 'čl. ',
  decision: 'Rozhodnutie',
  scope: 'Pre',
  companyWide: 'celú spoločnosť',
  reason: 'Dôvod',
  person: 'Zamestnanec',
  method: 'Spôsob',
  trainer: 'Školiteľ',
  signed: 'Potvrdené heslom',
  yes: 'áno',
  requested: 'Požiadané',
  signatures: 'Podpisy',
  copyNo: 'Č.',
  issuedTo: 'Vydané pre',
  issued: 'Vydané',
  withdrawnAt: 'Stiahnuté',
  'status.draft': 'návrh',
  'status.effective': 'platný',
  'status.review': 'na revízii',
  'status.obsolete': 'neplatný',
  'outcome.no-change': 'bez zmeny',
  'outcome.update-needed': 'treba upraviť',
  'outcome.updated': 'upravené',
  'kind.upcoming': 'pripravované znenie',
  'kind.new-version': 'nové znenie',
  'kind.check': 'kontrola',
  'kind.repealed': 'zrušený predpis',
  'chst.new': 'nové',
  'chst.reviewing': 'posudzuje sa',
  'chst.resolved': 'uzavreté',
  'dec.na': 'na spoločnosť sa nevzťahuje',
  'dec.ours': 'platí dokument spoločnosti',
  'method.session': 'školenie',
  'method.reading': 'prečítanie a potvrdenie',
  'method.onjob': 'na pracovisku',
  'method.self': 'samoštúdium',
  'method.signed': 'vlastnoručný podpis na hárku',
  'apr.pending': 'čaká',
  'apr.approved': 'schválené',
  'apr.rejected': 'zamietnuté',
  'apr.cancelled': 'zrušené',
  'copy.valid': 'platná',
  'copy.withdraw': 'stiahnuť',
  'copy.withdrawn': 'stiahnutá',
  notices: 'Oznamy úradov o stiahnutí liekov, zmeny sledovaných liekov a ich posúdenie',
  sumNotices: 'oznamov o stiahnutí na posúdenie',
  authority: 'Úrad',
  assessment: 'Posúdenie',
  measures: 'Opatrenia / poznámka',
  assessedAt: 'Posúdené',
  'nt.open': 'čaká na posúdenie',
  'nt.not-ours': 'netýka sa nás',
  'nt.done': 'opatrenia vykonané',
  'nt.noted': 'na vedomie'
};

const EN = {
  lang: 'en',
  fileName: 'Documentation-report',
  'sheet.summary': 'Summary',
  'sheet.register': 'Documents',
  'sheet.reviewsDue': 'Reviews due',
  'sheet.reviewsDone': 'Reviews done',
  'sheet.laws': 'Acts',
  'sheet.changes': 'Legislation changes',
  'sheet.decisions': 'Decisions',
  'sheet.trainingMissing': 'Missing training',
  'sheet.trainingRecords': 'Training',
  'sheet.approvals': 'Approvals',
  'sheet.copies': 'Controlled copies',
  'sheet.notices': 'Authority notices',
  title: 'Controlled documentation report',
  period: 'Period',
  periodAll: 'Whole period',
  generated: 'generated {date} in SOP Archív',
  footer: 'This report is an extract from SOP Archív. The full history (who, when, what) is in the app’s audit trail. Signatures in the app are confirmed with the user’s password.',
  none: 'No records.',
  sumDocs: 'controlled documents',
  sumEffective: '{n} effective',
  sumOverdue: 'reviews overdue',
  sumDue: 'reviews in the next 60 days',
  sumChanges: 'open legislation changes',
  sumDecisions: 'decisions "does not apply / our SOP applies"',
  sumTraining: 'missing trainings',
  sumCopies: 'copies to withdraw',
  register: 'Register of controlled documents',
  reviewsDue: 'Reviews overdue and due soon',
  reviewsDone: 'Reviews carried out',
  laws: 'Legal acts monitored',
  changes: 'Legislation changes and their assessment',
  decisions: "The company's decisions about provisions",
  trainingMissing: 'Missing training on the current version',
  trainingRecords: 'Training records',
  approvals: 'Approval of versions',
  copies: 'Controlled copies',
  code: 'Code',
  title_: 'Title',
  version: 'Version',
  status: 'Status',
  department: 'Department',
  effective: 'Effective from',
  review: 'Review by',
  approver: 'Approved by',
  approvedInApp: 'Approved in the app',
  trainingCol: 'Trained',
  lawsCol: 'Cites acts',
  days: 'Due',
  overdueBy: 'overdue by {n} days',
  inDays: 'in {n} days',
  date: 'Date',
  by: 'By',
  outcome: 'Outcome',
  next: 'Next review',
  notes: 'Notes',
  law: 'Act',
  lawVersion: 'Known version',
  checked: 'Checked',
  checkStatus: 'Check status',
  citingDocs: 'Documents',
  kind: 'Kind',
  effectiveFrom: 'Effective from',
  detected: 'Detected',
  affected: 'Affected docs',
  resolution: 'Closed',
  section: 'Provision',
  wholeAct: 'whole act',
  art: 'Art. ',
  decision: 'Decision',
  scope: 'For',
  companyWide: 'whole company',
  reason: 'Reason',
  person: 'Employee',
  method: 'Method',
  trainer: 'Trainer',
  signed: 'Confirmed with password',
  yes: 'yes',
  requested: 'Requested',
  signatures: 'Signatures',
  copyNo: 'No.',
  issuedTo: 'Issued to',
  issued: 'Issued',
  withdrawnAt: 'Withdrawn',
  'status.draft': 'draft',
  'status.effective': 'effective',
  'status.review': 'under review',
  'status.obsolete': 'obsolete',
  'outcome.no-change': 'no change',
  'outcome.update-needed': 'update needed',
  'outcome.updated': 'updated',
  'kind.upcoming': 'upcoming version',
  'kind.new-version': 'new version',
  'kind.check': 'check',
  'kind.repealed': 'repealed',
  'chst.new': 'new',
  'chst.reviewing': 'being assessed',
  'chst.resolved': 'closed',
  'dec.na': 'does not apply to the company',
  'dec.ours': "the company's document applies",
  'method.session': 'training session',
  'method.reading': 'read and confirmed',
  'method.onjob': 'on the job',
  'method.self': 'self-study',
  'method.signed': 'handwritten signature on the sheet',
  'apr.pending': 'pending',
  'apr.approved': 'approved',
  'apr.rejected': 'rejected',
  'apr.cancelled': 'cancelled',
  'copy.valid': 'valid',
  'copy.withdraw': 'to withdraw',
  'copy.withdrawn': 'withdrawn',
  notices: 'Authority recall notices, changes of watched products and their assessment',
  sumNotices: 'recall notices to assess',
  authority: 'Authority',
  assessment: 'Assessment',
  measures: 'Measures / note',
  assessedAt: 'Assessed',
  'nt.open': 'to assess',
  'nt.not-ours': 'not ours',
  'nt.done': 'measures taken',
  'nt.noted': 'noted'
};

module.exports = (lang) => {
  const L = lang === 'en' ? EN : SK;
  return new Proxy(L, { get: (o, k) => (k in o ? o[k] : String(k)) });
};
